// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc2601.NewRobotPneumatics;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Compressor pneumaticsMyCompressor;
    public static Solenoid pneumaticsSolenoidRetract;
    public static Solenoid pneumaticsSolenoidExtend;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        pneumaticsMyCompressor = new Compressor(1, 2, 1, 1);
	
        
        pneumaticsSolenoidRetract = new Solenoid(1, 1);
	LiveWindow.addActuator("Pneumatics", "SolenoidRetract", pneumaticsSolenoidRetract);
        
        pneumaticsSolenoidExtend = new Solenoid(1, 2);
	LiveWindow.addActuator("Pneumatics", "SolenoidExtend", pneumaticsSolenoidExtend);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        pneumaticsMyCompressor.start();
    }
}
