// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc2601.NewRobotGyro;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController drivetrainleft;
    public static SpeedController drivetrainright;
    public static RobotDrive drivetrainRobotDrive;
    public static Gyro gyro;
    public static Accelerometer accel;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainleft = new Jaguar(1, 1);
	LiveWindow.addActuator("Drivetrain", "left", (Jaguar) drivetrainleft);
        
        drivetrainright = new Jaguar(1, 2);
	LiveWindow.addActuator("Drivetrain", "right", (Jaguar) drivetrainright);
        
        drivetrainRobotDrive = new RobotDrive(drivetrainleft, drivetrainright);
	
        drivetrainRobotDrive.setSafetyEnabled(true);
        drivetrainRobotDrive.setExpiration(0.1);
        drivetrainRobotDrive.setSensitivity(0.5);
        drivetrainRobotDrive.setMaxOutput(1.0);
        

        gyro = new Gyro(1, 1);
        accel = new Accelerometer(1, 2);
        
	LiveWindow.addSensor("GyroAccel", "Gyro", gyro);
        System.out.println("------gyro instantiated");
        
        LiveWindow.addSensor("GyroAccel", "Accelerometer", accel);
        System.out.println("------accel instantiated");
        //gyroAccelGyro.setSensitivity(0.007);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
